server:
  port: 8078

jwt:
  access-expiration-time: 1296000
  refresh-expiration-time: 2592000
  secret-key: ${JWT_SECRET_KEY}

grpc:
  server:
    port: 50052

naver:
  develop-client-id: fZDbnomZT2TEeFgejPuJ
  develop-client-secret: ${NAVER_DEVELOP_SECRET_KEY}

logging:
  level:
    root: info

encryption:
  secret-key: ${ENCRYPTION_SECRET_KEY}
  salt: ${SALT}

spring:
  config:
    activate:
      on-profile: default, local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dayplancontentlocal
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  jackson:
    property-naming-strategy: SNAKE_CASE

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dayplanuser
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

s3:
  key-prefix: ${S3_KEY}
  bucket-name: ${BUCKET_NAME}
