logging:
  level:
    root: info

encryption:
  secret-key: ${ENCRYPTION_SECRET_KEY}
  salt: ${SALT}

spring:
  config:
    activate:
      on-profile: default, local

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dayplancontent
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

