server:
  port: 8078
  shutdown: graceful

logging:
  level:
    root: info

encryption:
  secret-key: ${ENCRYPTION_SECRET_KEY}
  salt: ${SALT}

springdoc:
  packages-to-scan: com.content.api
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

spring:
  config:
    activate:
      on-profile: default, local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dayplancontentlocal
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  jackson:
    property-naming-strategy: SNAKE_CASE

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  jpa:
    hibernate:
      ddl-auto: none

s3:
  key-prefix: ${S3_KEY}
  bucket-name: ${BUCKET_NAME}

user:
  server:
    url: ${USER_SERVER_URL}

server:
  port: ${SERVER_PORT}
  shutdown: graceful

grpc:
  content:
    server:
      port: 50052
  user:
    server:
      port: 50051
  server:
    port: 9090

logging:
  level:
    root: info

encryption:
  secret-key: ${ENCRYPTION_SECRET_KEY}
  salt: ${SALT}

springdoc:
  packages-to-scan: com.content.api
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha