package com.content.adapter

import org.springframework.boot.SpringBootConfiguration
import org.springframework.boot.autoconfigure.SpringBootApplication

@SpringBootConfiguration
@SpringBootApplication
class AdapterTestConfiguration
