version: 0.0
os: linux
files:
  - source: content-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/content-0.0.1-SNAPSHOT.jar
  - source: before_install.sh
    destination: /home/ec2-user/before_install.sh
  - source: application_start.sh
    destination: /home/ec2-user/application_start.sh

permissions:
  - object: content-0.0.1-SNAPSHOT.jar
    mode: "755"
    owner: ec2-user
    group: ec2-user
  - object: before_install.sh
    mode: "755"
    owner: ec2-user
    group: ec2-user
  - object: application_start.sh
    mode: "755"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: ec2-user
