package com.content.domain

import org.springframework.boot.SpringBootConfiguration
import org.springframework.boot.autoconfigure.SpringBootApplication

@SpringBootConfiguration
@SpringBootApplication
class DomainTestConfiguration
