name: dayplan-content
on:
  push:
    branches:
      - deploy
jobs:
  build:
    runs-on: ubuntu-20.04

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Tests and Build
        run: ./gradlew build --info

      - name: Archive deployment files
        run: |
          
          cp build/libs/content-0.0.1-SNAPSHOT.jar ./
          cp deploy/application_start.sh ./
          cp deploy/before_install.sh ./
          cp deploy/appspec.yml ./
          
          tar -cvf dayplan-content-app.tar \
            content-0.0.1-SNAPSHOT.jar \
            application_start.sh \
            before_install.sh \
            appspec.yml
          
          rm content-0.0.1-SNAPSHOT.jar application_start.sh before_install.sh appspec.yml

      - name: Upload TAR to S3
        run: |
          aws s3 cp \
            --region ap-northeast-2 \
            dayplan-content-app.tar s3://dayplan/dayplan-content-app.tar
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
