name: fe-dev
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Run Tests with H2 Database
        run: mvn test -Dspring.profiles.active=test

      - name: Sync Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            build/libs/content-0.0.1-SNAPSHOT.jar s3://dayplan \
            --delete
